plugins {
    //https://github.com/node-gradle/gradle-node-plugin/releases
    id "com.github.node-gradle.node" version "7.1.0"
}
node {
    version = '22.13.0' // https://nodejs.org/en/
    yarnVersion = '1.22.22' // https://yarnpkg.com/en/
    download = true
}

tasks.register('bootRun') {
    group = 'application'
    description = 'Run the client app (for use with gradle bootRun -parallel'
    dependsOn 'serve'
}

tasks.register('cleanNodeModules', Delete) {
    group = 'application'
    description = 'Clean node_modules and reinstall dependencies'
    delete layout.projectDirectory.dir('node_modules')
    delete layout.projectDirectory.file('package-lock.json')
}

tasks.register('yarnInstall', YarnTask) {
    group = 'application'
    description = 'Install yarn dependencies with force and check files'
    args = ['install', '--force', '--check-files']
}

tasks.register('serve', YarnTask) {
    group = 'application'
    description = 'Run the client app'
    dependsOn 'yarnInstall'
    args = ['serve']
}

tasks.register('pwaDev', YarnTask) {
    group = 'application'
    description = 'Run the client app in PWA development mode'
    dependsOn 'yarnInstall'
    args = ['run', 'pwa:dev']
}

tasks.register('build', YarnTask) {
    group = 'build'
    description = 'Build the client bundle'
    dependsOn 'yarn'
    args = ['run', 'build']
}

tasks.register('pwaBuild', YarnTask) {
    group = 'build'
    description = 'Build the client PWA bundle for production'
    dependsOn 'yarn'
    args = ['run', 'pwa:build']
}

tasks.register('lint', YarnTask) {
    group = 'build'
    description = 'Run eslint'
    dependsOn 'yarn'
    args = ['run', 'lint']
}
