buildscript {
    repositories {
        mavenLocal()
        maven { url "https://repo.grails.org/grails/core" }
        maven { url "https://plugins.gradle.org/m2/" }
    }
}
plugins {
    id 'groovy'
    id 'java-library'
    id 'idea'
}

repositories {
    mavenLocal()
    maven { url "https://repo.grails.org/grails/core" }
}

dependencies {
    implementation "org.apache.groovy:groovy-all:${property('groovy.version')}"
    implementation group: 'org.jeasy', name: 'easy-rules-core', version: '3.4.0'
}